routes/file.py
from flask import (
    Blueprint, render_template, 
    flash, url_for, redirect, request, 
    session, jsonify
)
from sqlalchemy.orm import load_only
from markupsafe import Markup
from werkzeug.utils import secure_filename
from flask_login import login_required, current_user
from .search import search
from .save import save_to_pdf
from ..models import User, File, Service, Report
from ..forms import FileForm, SearchForm, ReportForm
from ..helpers import generate_hash
from .. import db, Skittish, role_required, AVAILABLE_SERVICES, UPLOAD_DIR
import os
import base64
import json


file_blueprint = Blueprint('file', __name__)



#########################################
###       FILE action functions       ###
#########################################
def delete(id):
    resp = ('Delete success for FileID: {0}'.format(id), 'message')
    try:
        # fetch file by id
        file = File.query.options(load_only(File.id)).filter_by(id=id).first()
        if not file:
            resp = ('FileID: {0} does not exist.'.format(id), 'error')
            return resp
        
        # delete file from POST data
        db.session.delete(file)
        db.session.commit()

    except Exception as e:
        resp = (e, 'error')

    return resp


#########################################
###           FILE routes             ###
#########################################
@file_blueprint.route('/file')
@login_required
def index():
    # set message format as tuple
    # ('<MESSAGE>', '<message|success|info|>')
    message = None,
    # set error format as following
    # {'<key>': ['<message1>', '<message2>']}
    errors = None
    is_table = True
    table = []
    file_form = FileForm()
    search_form = SearchForm()
    # make sure file_search is empty when 
    # showall clicked or /file URL 
    if 'file_search' in session:
        session['file_search'] = ''
    # set item_per_page to 5
    search_form.item_per_page.data = 5
    table = search('files', search_form, 1)
    session['file_item_per_page'] = int(search_form.item_per_page.data)
    search_form.item_per_page.data = session['file_item_per_page']
        
    return render_template('file.html', 
                           form=search_form if is_table else file_form,
                           table=table, 
                           is_table=is_table,
                           available_services=AVAILABLE_SERVICES,
                           action='show',
                           message=message,
                           errors=errors)


@file_blueprint.route('/file/upload', methods=['POST'])
@login_required
def upload():
    file_upload = request.files['file']
    file = None
    file_form = FileForm()
    data = None
    filename = None
    sha256 = None
    if file_upload.filename == '':
        return jsonify({'file':'empty_file_selection'})
    try:
        data = file_upload.read()
        if len(data) >= 1024*1000*50:
            return jsonify({'file':'file_too_big_50MB_max'})
        
        sha256 = generate_hash(data, 'sha256')
        filename = secure_filename(file_upload.filename)
        if not filename:
            filename = sha256
        # with open(os.path.join(UPLOAD_DIR, filename), 'wb') as ud:
        #     ud.write(data)
        if not data:
            return jsonify({'file':'empty_file'})

        file = File.query.options(
            load_only(File.id, File.filename, File.filesize, File.md5, File.sha1, 
                      File.sha256, File.sha512, File.user_id, File.upload_date)
            ).filter_by(sha256=sha256).first()
        if file:
            flash('already exist - {0}'.format(file.sha256), 'error')
            return jsonify({
                'file': {
                    'filename': file.filename,
                    'filesize': file.filesize,
                    'md5': file.md5,
                    'sha1': file.sha1,
                    'sha256': file.sha256,
                    'sha512': file.sha512
                },
                'message': 'already exist - {0}'.format(file.sha256),
                'error': ''
            })
        else:
            # save it to database
            file = File(
                filename=filename,
                filesize=len(data),
                data=base64.b64encode(data),
                md5=generate_hash(data, 'md5'),
                sha1=generate_hash(data, 'sha1'),
                sha256=sha256,
                sha512=generate_hash(data, 'sha512'),
                user_id=current_user.id
            )
            # the file must be sent for report creation
            service = Service.query.filter_by(name='Report').first()
            file.services.append(service)
            # add it to database
            db.session.add(file)
            db.session.commit() # to get file.id before creating report

            # create the report entry for this file
            report = Report.query.filter_by(file_id=file.id).first()
            report_content = {
                    'title': 'This is a placeholder TITLE for {0}'.format(file.sha256),
                    'content': 'This is a placeholder CONTENT for {0}'.format(file.sha256),
                    'is_published': False
                }
            if not report:
                report = Report(
                    service_id=service.id,
                    file_id=file.id,
                    sha256=file.sha256,
                    content=json.dumps(report_content),
                    requested_by=current_user.id                    
                )
                # add it to database
                db.session.add(report)        
                # commit changes
                db.session.commit()

            print('Success')
        
    except Exception as e:
        flash('Error: {0}'.format(e), 'error')
        print(e)
        return jsonify({
            'file':{},
            'message':'',
            'error': '{0}'.format(e)
        })
    
    # # check if the saved data has still the same hash
    # check_it = File.query.filter_by(sha256=file.sha256).first()
    # if check_it.sha256 == generate_hash(base64.b64decode(check_it.data), 'sha256'):
    #     print('The same SHA256')
    # else:
    #     print('Not the same SHA256')

    return jsonify({
        'file': {
            'filename': file.filename,
            'filesize': file.filesize,
            'md5': file.md5,
            'sha1': file.sha1,
            'sha256': file.sha256,
            'sha512': file.sha512
        },
        'message': 'uploaded - {0}'.format(file_form.filename.data),
        'error': ''
    })


@file_blueprint.route('/file/<regex("view|delete|search"):action>', methods=['GET'])
@file_blueprint.route('/file/<regex("view|delete|search"):action>/<int:id>', methods=['GET'])
@file_blueprint.route('/file/<regex("view|delete|search"):action>/<int:id>/<int:per_page>', methods=['GET'])
@login_required
def file(action, id=None, per_page=0):
    # # set message format as tuple
    # # ('<MESSAGE>', '<message|success|info>')
    # message = None,
    # # set error format as following
    # # {'<key>': ['<message1>', '<message2>']}
    # errors = None
    is_table = False
    table = []
    services_available = {}
    file_form = FileForm()
    search_form = SearchForm()
    # in cases of action == search
    if id == None:
        page = 1
    else:
        page = id
    
    if per_page == 0:
        if 'file_item_per_page' in session:
            search_form.item_per_page.data = session['file_item_per_page']
        else:
            search_form.item_per_page.data = 5
            session['file_item_per_page'] = 5
    else:
        search_form.item_per_page.data = per_page
        session['file_item_per_page'] = per_page

    if action not in ['view', 'upload', 'delete','search']:
        flash('Not a valid action.', 'error')
        # return to current user profile
        if request.referrer:
            return redirect(request.referrer)
        else:
            return redirect(url_for('user.index'))
        
    try:
        match action:
            case 'upload':
                pass #to-do

            case 'search':
                if 'file_search' in session:
                    search_form.search.data = session['file_search']
                table = search('files', search_form, page)
                is_table = True
                
            case _:
                # get file object by id
                file_obj = File.query.options(
                    load_only(File.id, File.filename, File.filesize, File.md5, File.sha1, 
                              File.sha256, File.sha512, File.user_id, File.upload_date)
                              ).filter_by(id=id).first()
                # check the role of current_user
                # the file cannot be viewed if the current_user.id
                # is only submitter
                if 'submitter' in [r.name for r in current_user.roles] and len(current_user.roles) == 1:
                    if file_obj.user_id != current_user.id:
                        flash('You don\'t have the permission to {0} this file.'.format(action), 'error')
                        return render_template('file.html', 
                           form=search_form,
                           table=table, 
                           is_table=True,
                           available_services=AVAILABLE_SERVICES,
                           action=action)

                # transform file object services to {service_name: service_id}
                file_services = {}
                for s in file_obj.services:
                    service = Service.query.filter_by(id=s.id).first()
                    if not service:
                        continue
                    file_services[service.name] = service.id

                # fill FileForm fields with file object data
                file_form.id.data = file_obj.id
                file_form.filename.data = file_obj.filename

routes/login.py
from flask import (
    Blueprint, render_template, redirect, 
    request, url_for, flash, session
)
from flask_login import login_user, confirm_login, current_user
from ..helpers import check_password_hash
from ..models import User, Role, Report, File
from ..forms import LoginForm



tables = [
    User.__tablename__,
    Role.__tablename__,
    File.__tablename__,
    Report.__tablename__
]
login_blueprint = Blueprint('login', __name__)


@login_blueprint.route('/login')
def index():
    session['tables'] = sorted(tables)
    login_form = LoginForm(request.form)
    # Already logged-in
    if current_user.is_authenticated:
        flash('You are already logged-in.', 'message')
        return redirect(url_for('user.index'))
    
    return render_template('login.html', form=login_form)


@login_blueprint.route('/login', methods=['GET'])
def login():
    session['tables'] = tables
    login_form = LoginForm(request.form)
    # Already logged-in
    if current_user.is_authenticated:
        flash('You are already logged-in.', 'message')
        return redirect(url_for('user.index'))
    
    return render_template('login.html', form=login_form, error=login_form.errors)


@login_blueprint.route('/login', methods=['POST'])
def login_post():
    login_form = LoginForm(request.form)
    if not login_form.validate():
        return render_template('login.html', form=login_form, errors=login_form.errors)
    
    if not login_form.email.data or login_form.email.data == '':
        flash('Please enter email address.', 'error')
        return render_template('login.html', form=login_form)
    
    if not login_form.password.data or login_form.password.data == '':
        flash('Please enter password.', 'error')
        return render_template('login.html', form=login_form)
    
    user = User.query.filter_by(email=login_form.email.data).first()

    if not user.is_active:
        flash('Login failed. This account is not active.', 'error')
        return render_template('login.html', form=login_form)
        
    if not user:
        flash('Login failed. Please check your email address.', 'error')
        return render_template('login.html', form=login_form)
    
    if not check_password_hash(user.password, login_form.password.data.encode('utf-8')):
        flash('Login failed. Email address does not match with password.', 'error')
        return render_template('login.html', form=login_form)
    
    login_user(user, remember=login_form.remember_me)
    
    if 'admin' in [n.name for n in user.roles]:
        setattr(current_user, 'is_admin', True)
        session['is_admin'] = True
    else:
        setattr(current_user, 'is_admin', False)
        session['is_admin'] = False
    
    
    return redirect(url_for('user.index'))

routes/signup.py
from flask import (
    Blueprint, render_template, 
    redirect, url_for, request, flash
)
from ..models import User, Role
from ..helpers import generate_hash
from .. import db
from ..forms import SignUpForm



signup_blueprint = Blueprint('signup', __name__)


@signup_blueprint.route('/signup')
def index():
    form = SignUpForm()
    return render_template('signup.html', form=form)


@signup_blueprint.route('/signup')
def signup():
    signup_form = SignUpForm(request.form)
    return render_template('signup.html', form=signup_form)


@signup_blueprint.route('/signup', methods=['POST'])
def signup_post():
    signup_form = SignUpForm(request.form)
    if not signup_form.validate():
        return render_template('signup.html', form=signup_form, errors=signup_form.errors)

    user = User.query.filter_by(email=signup_form.email.data).first()
    if user:
        flash('Email address already exist.', 'error')
        return render_template('signup.html', form=signup_form)
    
    # create a new user with the form data. 
    # Hash the password so the plaintext version isn't saved.
    new_user = User(
        email=signup_form.email.data, 
        name=signup_form.name.data, 
        password=generate_hash(signup_form.password.data.encode('utf-8'), method='sha256')
    )
    resp = ('Successfully created the account.', 'message')
    try:
        # add default role (Analyst)
        r = Role.query.filter_by(name='submitter').first()
        # add the new user to the database
        new_user.roles.append(r)
        db.session.add(new_user)
        db.session.commit()
    except:
        resp = ('Error creating the account.', 'error')    
    
    flash(resp[0], resp[1])
    return redirect(url_for('login.index'))

templates/_file_table.html
{% block file_table %}
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
  <div class="container-fluid">
    <form name="search" class="d-flex center" method="POST" role="search" action="/file/search">
      <input id="csrf_token" type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <input id="search" class="form-control me-2" type="search" name="search" style="width: 570px;" 
      placeholder="SHA256 or Filename" aria-label="Search"
      {% if form.search.data %}
      value="{{form.search.data}}"
      {% endif %}
      >
      <select class="form-select me-2" style="width:170px;" name="item_per_page" aria-label="Item per page select">
        <option>Items per page</option>
        {% for i in range(5) %}
          {% if table.per_page == i+1 %}
          <option value="{{i+1}}" selected>{{i+1}} Items per page</option>
          {% else %}
          <option value="{{i+1}}">{{i+1}} Items per page</option>
          {% endif %}
        {% endfor %}
      </select>
      <button class="btn btn-outline-success" type="submit" style="margin-right: 3px;">Search</button>
      <a href="{{url_for('file.index')}}" class="btn btn-outline-success" role="button">Show All</a>
    </form>
  </div>
</nav>
{% if table %}
<div style="overflow-x: auto;">
  <nav aria-label="File pagination Top">
    <ul class="pagination">
      {% if table.has_prev %}
      <li class="page-item"><a class="page-link" href="/file/search/{{table.page-1}}">Previous</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
      {% endif %}
      {% for page in table.iter_pages() %}
        {% if page %}
          {% if page != table.page %}
            <li class="page-item"><a class="page-link" href="/file/search/{{page}}">{{page}}</a></li>
          {% else %}
            <li class="page-item active"><a class="page-link" href="#">{{page}}</a></li>
          {% endif %}
        {% else %}
          <span class="ellipsis">...</span>
        {% endif %}
      {% endfor %}
      {% if table.has_next %}
      <li class="page-item"><a class="page-link" href="/file/search/{{table.page+1}}">Next</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
      <div class="dropdown">
        <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Items per page
        </button>
        <ul class="dropdown-menu">
          {% for i in range(5) %}
              {% if i == 0 %}
              <li><a class="dropdown-item" href="/file/search/1/{{i+1}}">{{i+1}} Item per page</a></li>
              {% else %}
              <li><a class="dropdown-item" href="/file/search/1/{{i+1}}">{{i+1}} Items per page</a></li>
              {% endif %}
            {% endfor %}
        </ul>
      </div>
      <li class="page-item"><a class="page-link">Total Items: {{table.total}}</a></li>
    </ul>
    <!-- <ul class="pagination">
      <li class="page-item"><a class="page-link">Total Items: {{table.total}}</a></li>
    </ul> -->
  </nav>
  <table class="table table-striped">
    <!-- Table Heading -->
    <thead class="text-center">
      <tr>
        <th>Id</th>
        <th>Filename</th>
        <th>SHA256</th>        
        <th>Uploaded By</th>
        <th>Upload Date</th>        
        <th>Actions</th>
      </tr>
    </thead>
    <tbody class="text-center">
    <!-- On Rows -->
      {% for file in table %}
      <tr>
        <td>{{file.id}}</td>
        <td class="tbltdEllipsis">{{file.filename}}</td>
        <td class="tbltdEllipsis"><a href="/file/view/{{file.id}}">{{file.sha256}}</a></td>
        <td>{{file.user_id}}</td>
        <td>{{file.upload_date}}</td>
        <td>
          <a class="link-offset-2 link-underline link-underline-opacity-0" href="/file/view/{{file.id}}">
            <i class="bi-eye text-decoration-none" style="font-size: 1em; color: cornflowerblue;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
              </svg>
            </i>
          </a>
          <a class="link-offset-2 link-underline link-underline-opacity-0" href="/file/delete/{{file.id}}">
            <i class="bi-trash text-decoration-none" style="font-size: 1em; color: cornflowerblue;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
              </svg>
            </i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <nav aria-label="File pagination Bottom">
    <ul class="pagination">
      {% if table.has_prev %}
      <li class="page-item"><a class="page-link" href="/file/search/{{table.page-1}}">Previous</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
      {% endif %}
      {% for page in table.iter_pages() %}
        {% if page %}
          {% if page != table.page %}
            <li class="page-item"><a class="page-link" href="/file/search/{{page}}">{{page}}</a></li>
          {% else %}
            <li class="page-item active"><a class="page-link" href="#">{{page}}</a></li>
          {% endif %}
        {% else %}
          <span class="ellipsis">...</span>
        {% endif %}
      {% endfor %}
      {% if table.has_next %}
      <li class="page-item"><a class="page-link" href="/file/search/{{table.page+1}}">Next</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
{% else %}
<div class="container justify-content-md-center" style="text-align: center;width:100%;">
  <h1>No Result</h1>
</div>
{% endif %}
{% endblock %}

templates/alert.html
{% block content %}
  <!-- <main class="form-signin w-100 m-auto"> -->
  {% set type = 'alert-success' %}
  {% with messages = get_flashed_messages(with_categories=True) %}
  {% if messages %}
  {% if messages[0][0] == 'error' %}
    {% set type = 'alert-danger' %}
  {% elif messages[0][0] == 'warning' %}
    {% set type = 'alert-warning' %}
  {% endif %}
    <div class="alert {{type}} alert-dismissible fade show" role="alert">  
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      {{messages[0][1]}}
    </div>
  {% endif %}
  {% endwith %}
  {% if errors %}
  {% for key in errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">  
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          {{ key }} - {{ errors[key][0] }}
    </div>
  {% endfor %}
  {% endif %}
  <!-- </main> -->
{% endblock %}

templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="container text-align-center">
  <h1 class="title text-center">
  {{ error.path }} - {{ error.status }} ({{ error.message }})
  </h1>
</div>
{% endblock%}

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div>
    <h1 class="text-center">
      Skittish - Repository of Reports
    </h1>
  </div>    
  <div>
    <!-- Alert Messages -->
    {% include "alert.html" %}
  </div>
  <div class="centered">
    <div class="row">
      <div class="document-editor__toolbar"></div>
    </div>
    <div class="row row-editor">
      <div class="editor-container">
        <div class="editor">
        </div>
    </div>
  </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div id="the-whole-thing" style="height:100%; width:100%;">
  <div id="content-left" style="float: left; width:25%;">&nbsp;</div>
  <div id="content-middle" style="float: left; width:50%; ">
    <div>
      <h1 class="text-center">
        &nbsp;
      </h1>
    </div>
    <div>
      <!-- Alert Messages -->
      {% include "alert.html" %}
    </div>
    <form method="post" action="/login">
      <input id="csrf_token" type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
      <div class="fw-normal text-muted mb-4"> New Here?
      <a href="/signup" class="text-primary fw-bold text-decoration-none">Create an Account</a>
      </div>

      <div class="form-floating mb-4" style="width: 300px;">
      <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com" 
      {% if form.email.data %}
          value="{{form.email.data}}"
      {% endif %}
      >
      <label for="floatingInput">Email address</label>
      </div>
      <div class="form-floating mb-4" style="width: 300px;">
      <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
      </div>

      <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" name="remember_me" value="remember" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
          <span class="align-items-center">Remember me 
              <a href="#" class="text-primary fw-bold text-decoration-none m-3">Forget Password?</a>
          </span>
      </label>
      <!-- <div class="fw-normal text-muted my-1">
          <a href="#" class="text-primary fw-bold text-decoration-none">Forget Password?</a>
      </div> -->
      </div>
      <button class="btn btn-primary w-10 py-2" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-body-secondary">&copy; 2023 - Skittish</p>
    </form>
  </div>
  <div id="content-right" style="float: left; width:25%; "></div>
</div>

{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
<div id="the-whole-thing" style="height:100%; width:100%;">
  <div id="content-left" style="float: left; width:25%;">&nbsp;</div>
  <div id="content-middle" style="float: left; width:50%; ">
    <div>
      <h1 class="text-center">
        &nbsp;
      </h1>
    </div>
    <div>
      <!-- Alert Messages -->
      {% include "alert.html" %}
    </div>
    <form method="post" action="/signup">
      <input id="csrf_token" type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <h1 class="h3 mb-3 fw-normal">Create Account</h1>
      <div class="form-floating mb-4">
          <input type="email" name="email" class="form-control" id="floatingInput" placeholder="add email address" 
          {% if form.email.data %}
            value={{form.email.data}}
          {% endif %}
          >
          <label for="floatingInput">Email address</label>
        </div>
      <div class="form-floating mb-4">
        <input type="text" name="name" class="form-control" id="floatingInput" placeholder="add name" 
        {% if form.name.data %}
          value={{form.name.data}}
        {% endif %}
        >
        <label for="floatingInput">Name</label>
      </div>
      <div class="form-floating mb-4">
        <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Password</label>
        <span class="password-info mt-2">Use 8 or more characters with a mix of letters, numbers & symbols.</span>
      </div>
      <div class="form-floating mb-4">
          <input type="password" name="confirm_password" class="form-control" id="floatingPassword" placeholder="Password">
          <label for="floatingPassword">Confirm Password</label>
      </div>
      <button class="btn btn-primary w-100 py-2" type="submit">Create</button>
      <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2023</p>
    </form>
  </div>
  <div id="content-right" style="float: left; width:25%; "></div>
</div>
{% endblock %}